import { Link, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { FooterDisclaimer } from '../components/Disclaimer.jsx'
import { localePath } from '../utils/localeRouting.js'

export default function Terms() {
  const { t } = useTranslation('common')
  const { lang } = useParams()
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="font-display text-2xl font-semibold text-compass-heading">{t('footer.termsOfService')}</h1>
      <p className="mt-4 text-sm leading-relaxed text-compass-slate">
        Coverage Compass is a prototype built to demonstrate a plain-language
        insurance coverage review tool. By using it, you agree to the terms below.
      </p>
      <h2 className="mt-8 font-display text-lg font-semibold text-compass-heading">
        Educational use only
      </h2>
      <p className="mt-3 text-sm leading-relaxed text-compass-slate">
        Coverage Compass is not an insurance company, agency, or broker. It does
        not sell, bind, cancel, or modify insurance policies, and nothing it
        produces is insurance, legal, or financial advice. Coverage summaries and
        gap flags are generated by AI analysis of your document's text when
        available, or by local pattern matching otherwise, and either way are not
        verified by a licensed professional.
      </p>
      <h2 className="mt-8 font-display text-lg font-semibold text-compass-heading">
        No warranty
      </h2>
      <p className="mt-3 text-sm leading-relaxed text-compass-slate">
        This is a prototype provided as-is, without warranty of any kind. Coverage
        Compass does not guarantee the accuracy or completeness of any summary,
        score, or gap it generates. Always verify details against your official
        policy documents and consult a licensed insurance professional before
        making coverage decisions.
      </p>
      <h2 className="mt-8 font-display text-lg font-semibold text-compass-heading">
        Your content
      </h2>
      <p className="mt-3 text-sm leading-relaxed text-compass-slate">
        How documents you upload are handled, including when they may be sent to
        a server for AI-powered analysis, is described in the Privacy Policy.
      </p>
      <div className="mt-10">
        <Link to={localePath(lang, '/')} className="text-sm font-medium text-compass-link">
          Back to Home
        </Link>
      </div>
      <div className="mt-10 border-t border-compass-line pt-6">
        <FooterDisclaimer />
      </div>
    </div>
  )
}
